[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vanguard-voice-bot"
version = "1.0.0"
description = "Vanguard Voice Bot for Twilio with ElevenLabs integration"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
